name: Build and Publish ZoneMinder Arch

on:
  push:
    branches: [ "main" ] # Déclenche le build lors d'un push sur main
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: archlinux
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Buildx est nécessaire pour la gestion avancée du cache

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Web Service
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/zoneminder-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/zoneminder-web:${{ github.sha }}
          # Utilisation du cache pour accélérer les builds futurs
          cache-from: type=gha
          cache-to: type=gha,mode=max
